package com.argility.dao.entity;


// THIS IS AN AUTOGENERATED CLASS
public class CashTranEntity {

	public String usrId;
	public Integer audId;
	public Integer ctranRefId;
	public Double ctranAmt;
	public Double ctranTax;
	public Boolean ctranFin;
	public String ctranUsrId;
	public Boolean ctranIsCashup;

	public CashTranEntity() {};

	public CashTranEntity(String usrId, Integer audId, Integer ctranRefId, 
				Double ctranAmt, Double ctranTax, Boolean ctranFin, 
				String ctranUsrId, Boolean ctranIsCashup) {
		this.usrId = usrId;
		this.audId = audId;
		this.ctranRefId = ctranRefId;
		this.ctranAmt = ctranAmt;
		this.ctranTax = ctranTax;
		this.ctranFin = ctranFin;
		this.ctranUsrId = ctranUsrId;
		this.ctranIsCashup = ctranIsCashup;
	}


	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	public Integer getAudId() {
		return this.audId;
	}

	public void setAudId(Integer audId) {
		this.audId = audId;
	}

	public Integer getCtranRefId() {
		return this.ctranRefId;
	}

	public void setCtranRefId(Integer ctranRefId) {
		this.ctranRefId = ctranRefId;
	}

	public Double getCtranAmt() {
		return this.ctranAmt;
	}

	public void setCtranAmt(Double ctranAmt) {
		this.ctranAmt = ctranAmt;
	}

	public Double getCtranTax() {
		return this.ctranTax;
	}

	public void setCtranTax(Double ctranTax) {
		this.ctranTax = ctranTax;
	}

	public Boolean getCtranFin() {
		return this.ctranFin;
	}

	public void setCtranFin(Boolean ctranFin) {
		this.ctranFin = ctranFin;
	}

	public String getCtranUsrId() {
		return this.ctranUsrId;
	}

	public void setCtranUsrId(String ctranUsrId) {
		this.ctranUsrId = ctranUsrId;
	}

	public Boolean getCtranIsCashup() {
		return this.ctranIsCashup;
	}

	public void setCtranIsCashup(Boolean ctranIsCashup) {
		this.ctranIsCashup = ctranIsCashup;
	}


}
