package com.argility.dao.entity;

import java.sql.*;

// THIS IS AN AUTOGENERATED CLASS
public class CupTendEntity {

	public Integer audId;
	public Integer tendTyp;
	public Double cupTend;
	public Double cupChng;
	public String payrId;
	public String payrName;
	public String payrBranch;
	public String payrAccount;
	public Boolean payrIsCleared;
	public String payrReference;
	public String payrCrdkrdTyp;
	public Timestamp payrCrdkrdExpDte;
	public String tendstTyp;
	public String couponTyp;
	public String couponNo;

	public CupTendEntity() {};

	public CupTendEntity(Integer audId, Integer tendTyp, Double cupTend, 
				Double cupChng, String payrId, String payrName, 
				String payrBranch, String payrAccount, Boolean payrIsCleared, 
				String payrReference, String payrCrdkrdTyp, Timestamp payrCrdkrdExpDte, 
				String tendstTyp, String couponTyp, String couponNo) {
		this.audId = audId;
		this.tendTyp = tendTyp;
		this.cupTend = cupTend;
		this.cupChng = cupChng;
		this.payrId = payrId;
		this.payrName = payrName;
		this.payrBranch = payrBranch;
		this.payrAccount = payrAccount;
		this.payrIsCleared = payrIsCleared;
		this.payrReference = payrReference;
		this.payrCrdkrdTyp = payrCrdkrdTyp;
		this.payrCrdkrdExpDte = payrCrdkrdExpDte;
		this.tendstTyp = tendstTyp;
		this.couponTyp = couponTyp;
		this.couponNo = couponNo;
	}


	public Integer getAudId() {
		return this.audId;
	}

	public void setAudId(Integer audId) {
		this.audId = audId;
	}

	public Integer getTendTyp() {
		return this.tendTyp;
	}

	public void setTendTyp(Integer tendTyp) {
		this.tendTyp = tendTyp;
	}

	public Double getCupTend() {
		return this.cupTend;
	}

	public void setCupTend(Double cupTend) {
		this.cupTend = cupTend;
	}

	public Double getCupChng() {
		return this.cupChng;
	}

	public void setCupChng(Double cupChng) {
		this.cupChng = cupChng;
	}

	public String getPayrId() {
		return this.payrId;
	}

	public void setPayrId(String payrId) {
		this.payrId = payrId;
	}

	public String getPayrName() {
		return this.payrName;
	}

	public void setPayrName(String payrName) {
		this.payrName = payrName;
	}

	public String getPayrBranch() {
		return this.payrBranch;
	}

	public void setPayrBranch(String payrBranch) {
		this.payrBranch = payrBranch;
	}

	public String getPayrAccount() {
		return this.payrAccount;
	}

	public void setPayrAccount(String payrAccount) {
		this.payrAccount = payrAccount;
	}

	public Boolean getPayrIsCleared() {
		return this.payrIsCleared;
	}

	public void setPayrIsCleared(Boolean payrIsCleared) {
		this.payrIsCleared = payrIsCleared;
	}

	public String getPayrReference() {
		return this.payrReference;
	}

	public void setPayrReference(String payrReference) {
		this.payrReference = payrReference;
	}

	public String getPayrCrdkrdTyp() {
		return this.payrCrdkrdTyp;
	}

	public void setPayrCrdkrdTyp(String payrCrdkrdTyp) {
		this.payrCrdkrdTyp = payrCrdkrdTyp;
	}

	public Timestamp getPayrCrdkrdExpDte() {
		return this.payrCrdkrdExpDte;
	}

	public void setPayrCrdkrdExpDte(Timestamp payrCrdkrdExpDte) {
		this.payrCrdkrdExpDte = payrCrdkrdExpDte;
	}

	public String getTendstTyp() {
		return this.tendstTyp;
	}

	public void setTendstTyp(String tendstTyp) {
		this.tendstTyp = tendstTyp;
	}

	public String getCouponTyp() {
		return this.couponTyp;
	}

	public void setCouponTyp(String couponTyp) {
		this.couponTyp = couponTyp;
	}

	public String getCouponNo() {
		return this.couponNo;
	}

	public void setCouponNo(String couponNo) {
		this.couponNo = couponNo;
	}


}
