package com.argility.dao.entity;


// THIS IS AN AUTOGENERATED CLASS
public class PettyDrawEntity {

	public String usrId;
	public Integer audId;

	public PettyDrawEntity() {};

	public PettyDrawEntity(String usrId, Integer audId) {
		this.usrId = usrId;
		this.audId = audId;
	}


	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	public Integer getAudId() {
		return this.audId;
	}

	public void setAudId(Integer audId) {
		this.audId = audId;
	}


}
