package com.argility.dao.jdbcimpl.base;

import com.argility.master.dao.AbstractSpringJdbcDAO;
import com.argility.dao.entity.CupTendEntity;

// THIS IS AN AUTOGENERATED CLASS
public class CupTendBaseJdbcImplDAO extends AbstractSpringJdbcDAO<CupTendEntity> {

	public static final String TABLE_NAME = "cup_tend";
	public static final String[] COLUMN_NAMES = new String[] {
			"aud_id",
			"tend_typ",
			"cup_tend",
			"cup_chng",
			"payr_id",
			"payr_name",
			"payr_branch",
			"payr_account",
			"payr_is_cleared",
			"payr_reference",
			"payr_crdkrd_typ",
			"payr_crdkrd_exp_dte",
			"tendst_typ",
			"coupon_typ",
			"coupon_no"
			};

	public static final String[] PK_COLUMNS = new String[] {};
	public static final String[] INCREMENT_ON_UPDATE_COLUMNS = new String[] {};



	@Override
	protected String getTableName() {
		return TABLE_NAME;
	}

	@Override
	protected String[] getColumnNames() {
		return COLUMN_NAMES;
	}

	@Override
	protected String[] getPrimaryKeyColumns() {
		return PK_COLUMNS;
	}

	@Override
	protected String[] getIncrementOnUpdateColumns() {
		return INCREMENT_ON_UPDATE_COLUMNS;
	}


}
