package com.argility.dao;

import com.argility.master.dao.BasicEntityDAO;
import com.argility.dao.entity.CashTranEntity;

// THIS IS AN AUTOGENERATED CLASS
public interface CashTranDAO extends BasicEntityDAO<CashTranEntity> {




}
