package com.argility.dao;

import com.argility.master.dao.BasicEntityDAO;
import com.argility.dao.entity.CashTillEntity;

// THIS IS AN AUTOGENERATED CLASS
public interface CashTillDAO extends BasicEntityDAO<CashTillEntity> {




}
