package com.argility.dao;

import com.argility.master.dao.BasicEntityDAO;
import com.argility.dao.entity.CupTendEntity;

// THIS IS AN AUTOGENERATED CLASS
public interface CupTendDAO extends BasicEntityDAO<CupTendEntity> {




}
