//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.23 at 08:52:14 PM SAST 
//


package com.argility.master.trxengine.header;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="taxAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transAmt",
    "taxAmt"
})
@XmlRootElement(name = "docValueData01")
public class DocValueData01 {

    protected double transAmt;
    protected double taxAmt;

    /**
     * Gets the value of the transAmt property.
     * 
     */
    public double getTransAmt() {
        return transAmt;
    }

    /**
     * Sets the value of the transAmt property.
     * 
     */
    public void setTransAmt(double value) {
        this.transAmt = value;
    }

    /**
     * Gets the value of the taxAmt property.
     * 
     */
    public double getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     */
    public void setTaxAmt(double value) {
        this.taxAmt = value;
    }

}
