//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.23 at 08:52:14 PM SAST 
//


package com.argility.master.trxengine.header;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.argility.master.trxengine.header package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.argility.master.trxengine.header
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RefToInfo01 }
     * 
     */
    public RefToInfo01 createRefToInfo01() {
        return new RefToInfo01();
    }

    /**
     * Create an instance of {@link TransData01 }
     * 
     */
    public TransData01 createTransData01() {
        return new TransData01();
    }

    /**
     * Create an instance of {@link OboInData01 }
     * 
     */
    public OboInData01 createOboInData01() {
        return new OboInData01();
    }

    /**
     * Create an instance of {@link SeqD01 }
     * 
     */
    public SeqD01 createSeqD01() {
        return new SeqD01();
    }

    /**
     * Create an instance of {@link ClientActH01 }
     * 
     */
    public ClientActH01 createClientActH01() {
        return new ClientActH01();
    }

    /**
     * Create an instance of {@link ActH01 }
     * 
     */
    public ActH01 createActH01() {
        return new ActH01();
    }

    /**
     * Create an instance of {@link DocValueData01 }
     * 
     */
    public DocValueData01 createDocValueData01() {
        return new DocValueData01();
    }

    /**
     * Create an instance of {@link UiD01 }
     * 
     */
    public UiD01 createUiD01() {
        return new UiD01();
    }

    /**
     * Create an instance of {@link OboOutData01 }
     * 
     */
    public OboOutData01 createOboOutData01() {
        return new OboOutData01();
    }

}
