//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.23 at 08:52:14 PM SAST 
//

package com.argility.master.trxengine.header;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audit" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="finProcPer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grpCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "audit", "finProcPer", "branchCode",
		"grpCode" })
@XmlRootElement(name = "seqD01")
public class SeqD01 {

	@XmlElement(required = true, type = String.class)
	@XmlSchemaType(name = "integer")
	protected Integer audit;
	@XmlElement(required = true)
	protected String finProcPer;
	@XmlElement(required = true)
	protected String branchCode;
	protected String grpCode;

	/**
	 * Gets the value of the audit property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Integer getAudit() {
		return audit;
	}

	/**
	 * Sets the value of the audit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAudit(Integer value) {
		this.audit = value;
	}

	/**
	 * Gets the value of the finProcPer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFinProcPer() {
		return finProcPer;
	}

	/**
	 * Sets the value of the finProcPer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFinProcPer(String value) {
		this.finProcPer = value;
	}

	/**
	 * Gets the value of the branchCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBranchCode() {
		return branchCode;
	}

	/**
	 * Sets the value of the branchCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBranchCode(String value) {
		this.branchCode = value;
	}

	/**
	 * Gets the value of the grpCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGrpCode() {
		return grpCode;
	}

	/**
	 * Sets the value of the grpCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGrpCode(String value) {
		this.grpCode = value;
	}

}
