//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.23 at 08:52:14 PM SAST 
//


package com.argility.master.trxengine.header;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actionType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="isFinancial" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="docDate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="docNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refDocNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="buildNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isCredit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actionType",
    "isFinancial",
    "docDate",
    "docNo",
    "refDocNo",
    "buildNumber",
    "isCredit"
})
@XmlRootElement(name = "transData01")
public class TransData01 {

    @XmlElement(required = true, type = String.class)
    @XmlSchemaType(name = "integer")
    protected Integer actionType;
    protected boolean isFinancial;
    protected long docDate;
    @XmlElement(required = true)
    protected String docNo;
    protected String refDocNo;
    protected String buildNumber;
    protected Boolean isCredit;

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionType(Integer value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the isFinancial property.
     * 
     */
    public boolean isIsFinancial() {
        return isFinancial;
    }

    /**
     * Sets the value of the isFinancial property.
     * 
     */
    public void setIsFinancial(boolean value) {
        this.isFinancial = value;
    }

    /**
     * Gets the value of the docDate property.
     * 
     */
    public long getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     * 
     */
    public void setDocDate(long value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the docNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * Sets the value of the docNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNo(String value) {
        this.docNo = value;
    }

    /**
     * Gets the value of the refDocNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDocNo() {
        return refDocNo;
    }

    /**
     * Sets the value of the refDocNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDocNo(String value) {
        this.refDocNo = value;
    }

    /**
     * Gets the value of the buildNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildNumber() {
        return buildNumber;
    }

    /**
     * Sets the value of the buildNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildNumber(String value) {
        this.buildNumber = value;
    }

    /**
     * Gets the value of the isCredit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCredit() {
        return isCredit;
    }

    /**
     * Sets the value of the isCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCredit(Boolean value) {
        this.isCredit = value;
    }

}
