package com.argility.dao.jdbcimpl;

import com.argility.dao.CashTranDAO;
import com.argility.dao.jdbcimpl.base.CashTranBaseJdbcImplDAO;

// THIS IS AN AUTOGENERATED CLASS
public class CashTranJdbcImplDAO extends CashTranBaseJdbcImplDAO implements CashTranDAO  {




}
