package com.argility.dao.jdbcimpl;

import com.argility.dao.CashTillDAO;
import com.argility.dao.jdbcimpl.base.CashTillBaseJdbcImplDAO;

// THIS IS AN AUTOGENERATED CLASS
public class CashTillJdbcImplDAO extends CashTillBaseJdbcImplDAO implements CashTillDAO  {




}
