package com.argility.dao.jdbcimpl;

import com.argility.dao.CupTendDAO;
import com.argility.dao.jdbcimpl.base.CupTendBaseJdbcImplDAO;

// THIS IS AN AUTOGENERATED CLASS
public class CupTendJdbcImplDAO extends CupTendBaseJdbcImplDAO implements CupTendDAO  {




}
