package com.argility.dao.jdbcimpl;

import com.argility.dao.PettyDrawDAO;
import com.argility.dao.jdbcimpl.base.PettyDrawBaseJdbcImplDAO;

// THIS IS AN AUTOGENERATED CLASS
public class PettyDrawJdbcImplDAO extends PettyDrawBaseJdbcImplDAO implements PettyDrawDAO  {




}
